# Generated by Django 2.1.7 on 2019-03-13 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('skill', models.CharField(max_length=100, verbose_name='기술')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AlterField(
            model_name='major',
            name='title',
            field=models.CharField(max_length=100, verbose_name='전공명'),
        ),
        migrations.AddField(
            model_name='student',
            name='major_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Major', verbose_name='전공'),
        ),
    ]
