# Generated by Django 2.1.7 on 2019-03-05 03:41

import blog.models
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_person_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact_info',
            field=jsonfield.fields.JSONField(default=blog.models.Person.contact_default, verbose_name='aa'),
        ),
    ]
