# Generated by Django 2.1.7 on 2019-03-05 04:25

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190305_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact_info',
            field=models.TextField(default=blog.models.Person.contact_default, verbose_name='연락처'),
        ),
    ]
