# Generated by Django 2.1.7 on 2019-03-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_even_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='str_field',
            field=models.CharField(default='encore', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='str_field2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
