# Generated by Django 2.1.7 on 2019-03-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
