# Generated by Django 2.1.7 on 2019-03-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190311_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='book',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='book'),
        ),
        migrations.AddField(
            model_name='book',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='book/%Y/%m/%d'),
        ),
    ]
