# Generated by Django 2.1.7 on 2019-03-05 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190305_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTest',
            fields=[
                ('fAutoField', models.AutoField(primary_key=True, serialize=False)),
                ('fBigIntegerField', models.BigIntegerField(default=1)),
                ('fBooleanField', models.BooleanField(default=True)),
                ('fCharField', models.CharField(default='엔코아', max_length=30)),
                ('fDateField', models.DateField(default=datetime.date.today)),
                ('fDateTimeField', models.DateTimeField()),
                ('fDecimalField', models.DecimalField(decimal_places=4, default=1.7321, max_digits=10)),
                ('fEmailField', models.EmailField(default='email@example.com', max_length=254)),
                ('fFloatField', models.FloatField(default=1.7321)),
                ('fIntegerField', models.IntegerField(default=10)),
                ('fGenericIPAddressField', models.GenericIPAddressField(default=None, unpack_ipv4=True)),
                ('fNullBooleanField', models.NullBooleanField(default=True)),
                ('fPositiveIntegerField', models.PositiveIntegerField(default=100)),
                ('fPositiveSmallIntegerField', models.PositiveSmallIntegerField(default=50)),
                ('fSlugField', models.SlugField(default='slug', max_length=30)),
                ('fSmallIntegerField', models.SmallIntegerField(default=-50)),
                ('fTextField', models.TextField(default='text text text text text text text')),
                ('fURLField', models.URLField(default='http://localhost')),
            ],
        ),
    ]
