# Generated by Django 2.1.7 on 2019-03-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='year_school',
            field=models.CharField(choices=[('FR', '1학년'), ('SO', '2학년'), ('JR', '3학년'), ('SR', '4학년')], default='FR', max_length=2),
        ),
    ]
