# Generated by Django 2.1.7 on 2019-03-05 03:45

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190305_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact_info',
            field=jsonfield.fields.JSONField(default=dict, verbose_name='contactInfo'),
        ),
    ]
