# Generated by Django 2.1.7 on 2019-03-05 03:56

import blog.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190305_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=blog.models.Person.contact_default, verbose_name='연락처'),
        ),
    ]
