# Generated by Django 2.1.7 on 2019-03-05 06:11

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190305_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latlng',
            field=models.CharField(blank=True, help_text='위도와 경도를 입력하세요', max_length=100, validators=[blog.models.Post.latlng_validation]),
        ),
    ]
