# Generated by Django 2.1.7 on 2019-03-06 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
