# Generated by Django 2.1.7 on 2019-03-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190313_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='major_id',
            new_name='major',
        ),
    ]
